version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./internal/infra/database/migrations:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  ordersystem:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    env_file: ".env"
    command: go run cmd/ordersystem/main.go cmd/ordersystem/wire_gen.go
    depends_on:
      mysql:
        condition: service_started
        restart: true
      rabbitmq:
        condition: service_started
        restart: true
    ports:
      - 8000:8000
      - 50051:50051
      - 8080:8080
